"""
Reads every CSV in data/raw/, writes cleaned CSVs to data/clean/,
and generates sql/schema.sql with one table per CSV.

Strategy: every column as TEXT, except `id` (which becomes PRIMARY KEY where present).
This is intentional - we cast types in views/queries later, not at import.
"""

import os
import re
import csv
import pandas as pd
from pathlib import Path

RAW_DIR = Path("data/raw")
CLEAN_DIR = Path("data/clean")
SQL_FILE = Path("sql/schema.sql")

# Map each source CSV (relative path under data/raw) to its target Postgres table name.
# Files NOT in this map are skipped (e.g. the email logs).
FILE_TO_TABLE = {
    "Accounts/Accounts.csv":                                  "accounts",
    "Accounts/Account_contacts.csv":                          "account_contacts",
    "Contacts/Contacts.csv":                                  "contacts",
    "Contacts/Contact_emails.csv":                            "contact_emails",
    "Contacts/Contact_other_phone_numbers.csv":               "contact_phones",
    "Opportunities/Opportunities.csv":                        "opportunities",
    "Opportunities/Opportunity_contacts.csv":                 "opportunity_contacts",
    "Ios_cos items/Ios_cos items.csv":                        "leads",
    "Ios_cos items/Ios_cos item_emails.csv":                  "lead_emails",
    "Ios_cos items/Ios_cos item_other_phone_numbers.csv":     "lead_phones",
    "Users/Users.csv":                                        "users",
    "Users/User_roles.csv":                                   "user_roles",
    "Notes/Notes.csv":                                        "notes",
    "Notes/Note_targetables.csv":                             "note_targets",
    "Tasks/Tasks.csv":                                        "tasks",
    "Tasks/Task_targetables.csv":                             "task_targets",
    "Tasks/Task_collaborators.csv":                           "task_collaborators",
    "Meetings/Meetings.csv":                                  "meetings",
    "Meetings/Meeting_targetables.csv":                       "meeting_targets",
    "Meetings/Meeting_attendees.csv":                         "meeting_attendees",
    "Custom_sales_activities/Sales_activities.csv":           "sales_activities",
    "Custom_sales_activities/Salesactivity_targetables.csv":  "salesactivity_targets",
    "Custom_sales_activities/Salesactivity_collaborators.csv":"salesactivity_collaborators",
    "Call_logs/Call_logs.csv":                                "call_logs",
}


def normalise_column(name: str) -> str:
    """Turn 'Last activity date' into 'last_activity_date'. Postgres-friendly."""
    name = name.strip()
    name = re.sub(r"[^\w\s]", "", name)        # drop punctuation
    name = re.sub(r"\s+", "_", name)           # spaces -> underscores
    name = name.lower()
    name = re.sub(r"_+", "_", name).strip("_") # collapse multiple underscores
    return name or "blank"


def dedupe_columns(cols: list[str]) -> list[str]:
    """If two columns end up with the same name after normalising, suffix them."""
    seen = {}
    out = []
    for c in cols:
        if c in seen:
            seen[c] += 1
            out.append(f"{c}_{seen[c]}")
        else:
            seen[c] = 0
            out.append(c)
    return out


def process_file(rel_path: str, table_name: str) -> tuple[str, int, int]:
    src = RAW_DIR / rel_path
    dst = CLEAN_DIR / f"{table_name}.csv"
    dst.parent.mkdir(parents=True, exist_ok=True)

    # Read as strings only, treat blanks as empty strings (we'll convert to NULL on import).
    df = pd.read_csv(
        src,
        dtype=str,
        keep_default_na=False,
        na_values=[],
        engine="python",
        on_bad_lines="warn",
    )

    # Normalise column names
    new_cols = dedupe_columns([normalise_column(c) for c in df.columns])
    df.columns = new_cols

    # Strip whitespace from every cell
    df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

    # Write cleaned CSV with proper quoting (so Notes etc. with newlines survive)
    df.to_csv(
        dst,
        index=False,
        quoting=csv.QUOTE_ALL,
        encoding="utf-8",
    )

    # Build the CREATE TABLE statement
    col_defs = []
    has_id = "id" in df.columns
    for c in df.columns:
        if c == "id" and has_id:
            col_defs.append(f'    "{c}" TEXT PRIMARY KEY')
        else:
            col_defs.append(f'    "{c}" TEXT')
    ddl = (
        f"DROP TABLE IF EXISTS {table_name} CASCADE;\n"
        f"CREATE TABLE {table_name} (\n"
        + ",\n".join(col_defs)
        + "\n);\n"
    )

    return ddl, len(df), len(df.columns)


def main():
    CLEAN_DIR.mkdir(parents=True, exist_ok=True)
    SQL_FILE.parent.mkdir(parents=True, exist_ok=True)

    all_ddl = [
        "-- Auto-generated by scripts/clean_and_prepare.py",
        "-- Every column is TEXT. Cast in views/queries, not here.",
        "",
    ]
    summary = []

    for rel_path, table_name in FILE_TO_TABLE.items():
        src = RAW_DIR / rel_path
        if not src.exists():
            print(f"  MISSING: {rel_path}")
            continue
        ddl, n_rows, n_cols = process_file(rel_path, table_name)
        all_ddl.append(ddl)
        summary.append((table_name, n_rows, n_cols))
        print(f"  ok  {table_name:<32} rows={n_rows:>7}  cols={n_cols}")

    SQL_FILE.write_text("\n".join(all_ddl), encoding="utf-8")

    print("\nDone.")
    print(f"  Cleaned CSVs:  {CLEAN_DIR}")
    print(f"  Schema SQL:    {SQL_FILE}")
    print(f"  Tables:        {len(summary)}")
    print(f"  Total rows:    {sum(s[1] for s in summary):,}")


if __name__ == "__main__":
    main()