"""
Reads every CSV in data/raw/, writes cleaned CSVs to data/clean/,
and generates sql/schema.sql with one table per CSV.

Strategy:
  - Pre-scan with csv.reader to find true max column count (handles trailing
    unlabeled columns in Freshsales exports).
  - Pad headers with extra_N if data rows are wider than the header row.
  - Every column is TEXT.
  - No PRIMARY KEY constraints (archival data, duplicates allowed).
    Indexes on id columns are added in a separate post-load step.
"""

import csv
import re
from pathlib import Path
import pandas as pd

RAW_DIR = Path("data/raw")
CLEAN_DIR = Path("data/clean")
SQL_FILE = Path("sql/schema.sql")

FILE_TO_TABLE = {
    "Accounts/Accounts.csv":                                  "accounts",
    "Accounts/Account_contacts.csv":                          "account_contacts",
    "Contacts/Contacts.csv":                                  "contacts",
    "Contacts/Contact_emails.csv":                            "contact_emails",
    "Contacts/Contact_other_phone_numbers.csv":               "contact_phones",
    "Opportunities/Opportunities.csv":                        "opportunities",
    "Opportunities/Opportunity_contacts.csv":                 "opportunity_contacts",
    "Ios_cos items/Ios_cos items.csv":                        "leads",
    "Ios_cos items/Ios_cos item_emails.csv":                  "lead_emails",
    "Ios_cos items/Ios_cos item_other_phone_numbers.csv":     "lead_phones",
    "Users/Users.csv":                                        "users",
    "Users/User_roles.csv":                                   "user_roles",
    "Notes/Notes.csv":                                        "notes",
    "Notes/Note_targetables.csv":                             "note_targets",
    "Tasks/Tasks.csv":                                        "tasks",
    "Tasks/Task_targetables.csv":                             "task_targets",
    "Tasks/Task_collaborators.csv":                           "task_collaborators",
    "Meetings/Meetings.csv":                                  "meetings",
    "Meetings/Meeting_targetables.csv":                       "meeting_targets",
    "Meetings/Meeting_attendees.csv":                         "meeting_attendees",
    "Custom_sales_activities/Sales_activities.csv":           "sales_activities",
    "Custom_sales_activities/Salesactivity_targetables.csv":  "salesactivity_targets",
    "Custom_sales_activities/Salesactivity_collaborators.csv":"salesactivity_collaborators",
    "Call_logs/Call_logs.csv":                                "call_logs",
}


def normalise_column(name: str) -> str:
    name = name.strip()
    name = re.sub(r"[^\w\s]", "", name)
    name = re.sub(r"\s+", "_", name)
    name = name.lower()
    name = re.sub(r"_+", "_", name).strip("_")
    return name or "blank"


def dedupe_columns(cols):
    seen = {}
    out = []
    for c in cols:
        if c in seen:
            seen[c] += 1
            out.append(f"{c}_{seen[c]}")
        else:
            seen[c] = 0
            out.append(c)
    return out


def detect_max_columns(src: Path) -> tuple[list[str], int]:
    """Read once with csv.reader to find header + true max column count."""
    with open(src, "r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        max_cols = len(header)
        for row in reader:
            if len(row) > max_cols:
                max_cols = len(row)
    return header, max_cols


def process_file(rel_path: str, table_name: str):
    src = RAW_DIR / rel_path
    dst = CLEAN_DIR / f"{table_name}.csv"
    dst.parent.mkdir(parents=True, exist_ok=True)

    raw_header, max_cols = detect_max_columns(src)
    n_extra = max_cols - len(raw_header)

    padded_header = list(raw_header) + [f"extra_{i+1}" for i in range(n_extra)]
    normalised = dedupe_columns([normalise_column(c) for c in padded_header])

    df = pd.read_csv(
        src,
        dtype=str,
        keep_default_na=False,
        na_values=[],
        engine="python",
        on_bad_lines="warn",
        names=normalised,
        header=0,
    )
    df = df.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

    df.to_csv(
        dst,
        index=False,
        quoting=csv.QUOTE_ALL,
        encoding="utf-8",
    )

    col_defs = [f'    "{c}" TEXT' for c in df.columns]
    ddl = (
        f"DROP TABLE IF EXISTS {table_name} CASCADE;\n"
        f"CREATE TABLE {table_name} (\n"
        + ",\n".join(col_defs)
        + "\n);\n"
    )
    return ddl, len(df), len(df.columns), n_extra


def main():
    CLEAN_DIR.mkdir(parents=True, exist_ok=True)
    SQL_FILE.parent.mkdir(parents=True, exist_ok=True)

    all_ddl = [
        "-- Auto-generated by scripts/clean_and_prepare.py",
        "-- All columns TEXT. No PK constraints (archive data).",
        "",
    ]
    summary = []

    for rel_path, table_name in FILE_TO_TABLE.items():
        src = RAW_DIR / rel_path
        if not src.exists():
            print(f"  MISSING: {rel_path}")
            continue
        ddl, n_rows, n_cols, n_extra = process_file(rel_path, table_name)
        all_ddl.append(ddl)
        summary.append((table_name, n_rows, n_cols, n_extra))
        extra_note = f"  (+{n_extra} extra)" if n_extra else ""
        print(f"  ok  {table_name:<32} rows={n_rows:>7}  cols={n_cols}{extra_note}")

    # Indexes on id columns (where present) for query performance
    all_ddl.append("-- Indexes on id columns for lookup speed\n")
    for table_name, _, _, _ in summary:
        all_ddl.append(f"CREATE INDEX IF NOT EXISTS idx_{table_name}_id ON {table_name}(id);\n")

    SQL_FILE.write_text("\n".join(all_ddl), encoding="utf-8")

    print("\nDone.")
    print(f"  Total rows:  {sum(s[1] for s in summary):,}")
    print(f"  Tables:      {len(summary)}")


if __name__ == "__main__":
    main()