-- Auto-generated by scripts/clean_and_prepare.py
-- All columns TEXT. No PK constraints (archive data).

DROP TABLE IF EXISTS accounts CASCADE;
CREATE TABLE accounts (
    "id" TEXT,
    "college_name" TEXT,
    "number_of_students_in_final_year" TEXT,
    "spending_potential_of_the_college" TEXT,
    "website" TEXT,
    "phone" TEXT,
    "display_phone" TEXT,
    "address" TEXT,
    "city" TEXT,
    "state" TEXT,
    "zipcode" TEXT,
    "country" TEXT,
    "facebook" TEXT,
    "twitter" TEXT,
    "linkedin" TEXT,
    "last_contacted_time" TEXT,
    "last_contacted_mode" TEXT,
    "last_contacted_via_chat" TEXT,
    "last_activity_type" TEXT,
    "last_activity_date" TEXT,
    "recent_note" TEXT,
    "industry_type" TEXT,
    "business_type" TEXT,
    "territory" TEXT,
    "blank" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "active_sales_sequences" TEXT,
    "completed_sales_sequences" TEXT,
    "last_assigned_at" TEXT,
    "blank_1" TEXT,
    "blank_2" TEXT,
    "blank_3" TEXT,
    "parent_account_id" TEXT,
    "parent_account" TEXT,
    "owner_id" TEXT,
    "owner" TEXT,
    "created_by_id" TEXT,
    "created_by" TEXT,
    "updated_by_id" TEXT,
    "updated_by" TEXT,
    "import_id" TEXT,
    "type" TEXT,
    "client_code" TEXT,
    "gstin" TEXT,
    "district" TEXT,
    "directions_to_reach_college" TEXT,
    "local_commute_info" TEXT,
    "total_students_in_20232024" TEXT,
    "total_students_in_20242025" TEXT,
    "total_students_in_20252026" TEXT,
    "engg_sanctioned_intake" TEXT,
    "engg_seats_filled" TEXT,
    "engg_fees" TEXT,
    "arts_and_science_sanctioned_intake" TEXT,
    "arts_and_science_seats_filled" TEXT,
    "arts_and_science_fees" TEXT,
    "mgmt_sanctioned_intake" TEXT,
    "mgmt_seats_filled" TEXT,
    "mgmt_fees" TEXT,
    "dm_name" TEXT,
    "dm_designation" TEXT,
    "dm_contact_number" TEXT,
    "dm_mail_id" TEXT,
    "di1_name" TEXT,
    "di1_designation" TEXT,
    "di1_contact_number" TEXT,
    "di1_mail_id" TEXT,
    "di2_name" TEXT,
    "di2_designation" TEXT,
    "di2_contact_number" TEXT,
    "di2_mail_id" TEXT,
    "gate_keeper1_name" TEXT,
    "gate_keeper1_designation" TEXT,
    "gate_keeper1_contact_number" TEXT,
    "gate_keeper1_mail_id" TEXT,
    "gate_keeper2_name" TEXT,
    "gate_keeper2_designation" TEXT,
    "gate_keeper2_contact_details" TEXT,
    "gate_keeper2_mail_id" TEXT,
    "tpo_1_name" TEXT,
    "tpo_1_designation" TEXT,
    "tpo_1_contact_details" TEXT,
    "tpo_1_mail_id" TEXT,
    "tpo2_name" TEXT,
    "tpo2_designation" TEXT,
    "tpo2_contact_details" TEXT,
    "tpo2_mail_id" TEXT,
    "tpo3_name" TEXT,
    "tpo3_designation" TEXT,
    "tpo3_contact_details" TEXT,
    "tpo3_mail_id" TEXT,
    "top_recruiters_20252026" TEXT,
    "placement_20252026" TEXT,
    "avg_salary_range_20252026" TEXT,
    "does_the_college_run_their_own_training_programs_or_outsourced" TEXT,
    "what_programs_are_outsourced" TEXT,
    "mode" TEXT,
    "vendor_details" TEXT,
    "spend_per_student_approx" TEXT,
    "total_budget_approx" TEXT,
    "training_calendar" TEXT,
    "details_of_inhouse_training_program" TEXT,
    "name_to_be_mentioned_in_the_invoice" TEXT,
    "old_client_code_not_mandatory" TEXT,
    "credit_category" TEXT,
    "old_clientgroup_code" TEXT,
    "new_client_code" TEXT,
    "new_group_code" TEXT,
    "last_call_task_completed_date" TEXT,
    "cf_status" TEXT,
    "zone" TEXT,
    "dm_relationship_establishment" TEXT,
    "category_cst_reference" TEXT,
    "cst_owner" TEXT,
    "naacaccreditation" TEXT,
    "yearwise_strength_1stfinal_year" TEXT,
    "current_vendor_for_crt" TEXT,
    "tags" TEXT
);

DROP TABLE IF EXISTS account_contacts CASCADE;
CREATE TABLE account_contacts (
    "id" TEXT,
    "sales_account_id" TEXT,
    "contact_id" TEXT,
    "is_primary" TEXT
);

DROP TABLE IF EXISTS contacts CASCADE;
CREATE TABLE contacts (
    "id" TEXT,
    "first_name" TEXT,
    "full_name" TEXT,
    "disignation" TEXT,
    "department" TEXT,
    "work" TEXT,
    "mobile" TEXT,
    "has_authority" TEXT,
    "do_not_disturb" TEXT,
    "time_zone" TEXT,
    "address" TEXT,
    "city" TEXT,
    "state" TEXT,
    "zipcode" TEXT,
    "country" TEXT,
    "facebook" TEXT,
    "twitter" TEXT,
    "linkedin" TEXT,
    "medium" TEXT,
    "keyword" TEXT,
    "last_contacted_time" TEXT,
    "last_contacted_mode" TEXT,
    "last_contacted_via_chat" TEXT,
    "last_activity_type" TEXT,
    "last_activity_date" TEXT,
    "last_seen_on_web" TEXT,
    "ioscos_item_score" TEXT,
    "blank" TEXT,
    "blank_1" TEXT,
    "blank_2" TEXT,
    "blank_3" TEXT,
    "recent_note" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "source" TEXT,
    "campaign" TEXT,
    "territory" TEXT,
    "blank_4" TEXT,
    "status" TEXT,
    "blank_5" TEXT,
    "blank_6" TEXT,
    "blank_7" TEXT,
    "blank_8" TEXT,
    "blank_9" TEXT,
    "blank_10" TEXT,
    "blank_11" TEXT,
    "blank_12" TEXT,
    "blank_13" TEXT,
    "blank_14" TEXT,
    "active_sales_sequences" TEXT,
    "completed_sales_sequences" TEXT,
    "blank_15" TEXT,
    "web_forms" TEXT,
    "last_assigned_at" TEXT,
    "account_id" TEXT,
    "account" TEXT,
    "owner_id" TEXT,
    "owner" TEXT,
    "created_by_id" TEXT,
    "created_by" TEXT,
    "updated_by_id" TEXT,
    "updated_by" TEXT,
    "import_id" TEXT,
    "emails" TEXT,
    "last_spoken_date" TEXT,
    "role_type" TEXT,
    "relationship_status" TEXT,
    "tags" TEXT
);

DROP TABLE IF EXISTS contact_emails CASCADE;
CREATE TABLE contact_emails (
    "contact_id" TEXT,
    "email" TEXT,
    "primary" TEXT,
    "email_status" TEXT,
    "label" TEXT
);

DROP TABLE IF EXISTS contact_phones CASCADE;
CREATE TABLE contact_phones (
    "contact_id" TEXT,
    "other_phone_number" TEXT,
    "label" TEXT,
    "extra_1" TEXT
);

DROP TABLE IF EXISTS opportunities CASCADE;
CREATE TABLE opportunities (
    "id" TEXT,
    "opportunity_title" TEXT,
    "net_bv_value" TEXT,
    "currency" TEXT,
    "opportunity_value_in_base_currency" TEXT,
    "expected_close_date_of_the_deal" TEXT,
    "closed_date" TEXT,
    "collection_outstanding" TEXT,
    "last_activity_type" TEXT,
    "last_activity_date" TEXT,
    "recent_note" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "opportunity_pipeline" TEXT,
    "opportunity_stage" TEXT,
    "lost_reason" TEXT,
    "product" TEXT,
    "payment_status" TEXT,
    "territory" TEXT,
    "blank" TEXT,
    "mode_of_training" TEXT,
    "source" TEXT,
    "campaign" TEXT,
    "forecast_category" TEXT,
    "active_sales_sequences" TEXT,
    "completed_sales_sequences" TEXT,
    "web_form" TEXT,
    "upcoming_activities" TEXT,
    "opportunity_stage_updated_at" TEXT,
    "last_assigned_at" TEXT,
    "expected_opportunity_value" TEXT,
    "client_name_id" TEXT,
    "client_name" TEXT,
    "owner_id" TEXT,
    "owner" TEXT,
    "created_by_id" TEXT,
    "created_by" TEXT,
    "updated_by_id" TEXT,
    "updated_by" TEXT,
    "import_id" TEXT,
    "sale_closure_status" TEXT,
    "deal_number_to_be_updated_by_salesops" TEXT,
    "start_date_of_training" TEXT,
    "client_segment" TEXT,
    "college_address_exact_location" TEXT,
    "colleges_city" TEXT,
    "colleges_state" TEXT,
    "pincode" TEXT,
    "srm_trainers_to_contact" TEXT,
    "pricing_type" TEXT,
    "net_price_for_the_above_pricing_type" TEXT,
    "training_date_status" TEXT,
    "college_name" TEXT,
    "probability_status" TEXT,
    "no_of_competitors" TEXT,
    "client_response" TEXT,
    "cst_category" TEXT,
    "send_for_approval" TEXT,
    "next_follow_up_date" TEXT,
    "batchlist" TEXT,
    "mail_confirmation_attachment_status" TEXT,
    "projected_programs" TEXT,
    "year_of_passout" TEXT,
    "lead_source" TEXT,
    "type_of_oif" TEXT,
    "training_start_date" TEXT,
    "training_end_date" TEXT,
    "number_of_weeks" TEXT,
    "training_hours_per_batch_per_week" TEXT,
    "engagement_type" TEXT,
    "client_type" TEXT,
    "lead_generation_date" TEXT,
    "proposal_sent_status" TEXT,
    "proposal_sent_date" TEXT,
    "number_of_students_registered" TEXT,
    "number_of_batches" TEXT,
    "projected_ptd" TEXT,
    "expected_bv_automated" TEXT,
    "last_call_task_completed_date" TEXT,
    "number_of_students_as_per_the_attached_batch_list" TEXT,
    "department" TEXT,
    "maximum_students_per_batch" TEXT,
    "previous_oif_number_for_the_same_set_of_students" TEXT,
    "competitor_name_and_courses_handled_by_competitor_for_the_same_set_of_students" TEXT,
    "product_type" TEXT,
    "csac_drive_date" TEXT,
    "proposed_course" TEXT,
    "course_variant_mapping" TEXT,
    "aptitude_split_up_in_hours" TEXT,
    "technical_split_up_in_hours" TEXT,
    "programming_language" TEXT,
    "softskill_split_up_in_hours" TEXT,
    "training_hours_per_batch" TEXT,
    "training_days_per_batch" TEXT,
    "total_training_hours_of_program" TEXT,
    "total_trainer_days_of_the_program" TEXT,
    "training_dates" TEXT,
    "expected_week_of_execution" TEXT,
    "are_trainers_required" TEXT,
    "session_timings" TEXT,
    "session_timing_type" TEXT,
    "training_language_allowed" TEXT,
    "material_version" TEXT,
    "accommodation_provided_by" TEXT,
    "attendance_alert_to_be_escalated_if_attendance_drops_below_this_percentage" TEXT,
    "accommodation_type" TEXT,
    "whatsapp_group_for_students" TEXT,
    "feedback_to_be_administered" TEXT,
    "transport_stn_or_busstand_to_stay" TEXT,
    "transport_stay_to_college" TEXT,
    "meals_provided" TEXT,
    "infrastructure_expenses_if_any_projector_or_laptop_or_speakers" TEXT,
    "marketing_promotions_are_allowed_in_the_wa_group_created" TEXT,
    "local_commute" TEXT,
    "direction_to_reach_the_college" TEXT,
    "college_start_time_and_college_end_time" TEXT,
    "client_expectations" TEXT,
    "students_level" TEXT,
    "tpos_mindset_and_strategies" TEXT,
    "key_members_in_the_pt_team_who_controls_onground_training" TEXT,
    "are_tests_required" TEXT,
    "postassessment_test_mode_and_admin_details" TEXT,
    "number_of_freshgrad_tests_committed_or_required" TEXT,
    "preassessment_test_mode_and_admin_details" TEXT,
    "preassessment_test_date" TEXT,
    "midassessment_test_mode_and_admin_details" TEXT,
    "midassessment_test_date" TEXT,
    "postassessment_test_date" TEXT,
    "daily_or_misc_assessments_details_if_required" TEXT,
    "any_other_specifications" TEXT,
    "number_of_files_attached_in_this_opportunity_and_name_them" TEXT,
    "trainers_to_contact" TEXT,
    "logistics_related_contact" TEXT,
    "materials_to_be_addressed_to" TEXT,
    "invoice_and_collections_contact" TEXT,
    "minimum_number_of_students_to_be_billed" TEXT,
    "invoicing_type" TEXT,
    "invoicing_terms" TEXT,
    "details_about_special_case_invoicing" TEXT,
    "gross_price_per_student_or_per_trainer_day_or_lumpsum_or_per_trainer_per_hour_or_per_student_per_hour" TEXT,
    "gross_total_contract_value" TEXT,
    "address_to_send_invoice_hard_copy" TEXT,
    "email_address_to_send_invoice_soft_copy" TEXT,
    "payment_ownership" TEXT,
    "payment_type" TEXT,
    "payment_split_up_amount_with_due_date" TEXT,
    "advance_payment_details" TEXT,
    "credit_period_for_payment_after_receipt_of_invoice" TEXT,
    "payment_deadline" TEXT,
    "payment_mode" TEXT,
    "other_specifications_regarding_invoice_and_collection" TEXT,
    "financial_year" TEXT,
    "proforma_invoice" TEXT,
    "proforma_invoice_raised_on" TEXT,
    "tax_invoice" TEXT,
    "tax_invoice_raised_on" TEXT,
    "item_type" TEXT,
    "total_outstanding" TEXT,
    "ptd_price" TEXT,
    "client_name_auto" TEXT,
    "client_code_new" TEXT,
    "city" TEXT,
    "state" TEXT,
    "client_category" TEXT,
    "college_bucket" TEXT,
    "address" TEXT,
    "zipcode" TEXT,
    "directions_to_reach_college" TEXT,
    "client_history" TEXT,
    "local_commute_info" TEXT,
    "deal_type" TEXT,
    "gst_180" TEXT,
    "net_price" TEXT,
    "fy25_q4_estimated_contribution" TEXT,
    "cluster" TEXT,
    "tags" TEXT,
    "age_in_days" TEXT
);

DROP TABLE IF EXISTS opportunity_contacts CASCADE;
CREATE TABLE opportunity_contacts (
    "id" TEXT,
    "deal_id" TEXT,
    "contact_id" TEXT
);

DROP TABLE IF EXISTS leads CASCADE;
CREATE TABLE leads (
    "id" TEXT,
    "first_name" TEXT,
    "full_name_of_the_college" TEXT,
    "job_title" TEXT,
    "department" TEXT,
    "work" TEXT,
    "mobile" TEXT,
    "has_authority" TEXT,
    "do_not_disturb" TEXT,
    "time_zone" TEXT,
    "address" TEXT,
    "city" TEXT,
    "state" TEXT,
    "zipcode" TEXT,
    "country" TEXT,
    "facebook" TEXT,
    "twitter" TEXT,
    "linkedin" TEXT,
    "medium" TEXT,
    "keyword" TEXT,
    "last_contacted_time" TEXT,
    "last_contacted_mode" TEXT,
    "last_contacted_via_chat" TEXT,
    "last_activity_type" TEXT,
    "last_activity_date" TEXT,
    "last_seen_on_web" TEXT,
    "ioscos_item_score" TEXT,
    "recent_note" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "payment_stage" TEXT,
    "source" TEXT,
    "unqualified_reason" TEXT,
    "campaign" TEXT,
    "territory" TEXT,
    "blank" TEXT,
    "active_sales_sequences" TEXT,
    "completed_sales_sequences" TEXT,
    "web_forms" TEXT,
    "last_assigned_at" TEXT,
    "owner_id" TEXT,
    "owner" TEXT,
    "created_by_id" TEXT,
    "created_by" TEXT,
    "updated_by_id" TEXT,
    "updated_by" TEXT,
    "import_id" TEXT,
    "emails" TEXT,
    "account_name" TEXT,
    "account_address" TEXT,
    "account_city" TEXT,
    "account_state" TEXT,
    "account_zipcode" TEXT,
    "company_country" TEXT,
    "number_of_students" TEXT,
    "spending_potential_of_the_account" TEXT,
    "account_website" TEXT,
    "account_phone" TEXT,
    "education_institution_type" TEXT,
    "business_type" TEXT,
    "opportunity_name" TEXT,
    "opportunity_value" TEXT,
    "product_category" TEXT,
    "opportunity_currency" TEXT,
    "opportunity_value_in_base_currency" TEXT,
    "opportunity_expected_close_date" TEXT,
    "proforma_invoice" TEXT,
    "proforma_invoice_raised_date" TEXT,
    "tax_invoice" TEXT,
    "tax_invoice_raising_date" TEXT,
    "program_name" TEXT,
    "net_amount" TEXT,
    "gross_amount" TEXT,
    "payment_status" TEXT,
    "total_payment_received" TEXT,
    "collection_outstanding" TEXT,
    "item_type" TEXT,
    "deal_number" TEXT,
    "collection_outstanding_as_per_tracker" TEXT,
    "item_stage" TEXT,
    "next_action_item" TEXT,
    "next_followup_date" TEXT,
    "account_code" TEXT,
    "priority_account_name" TEXT,
    "approved_first_year_student_intake" TEXT,
    "student_enrollment_against_intake" TEXT,
    "current_training_model" TEXT,
    "current_training_spend" TEXT,
    "current_training_organisation" TEXT,
    "open_opportunities" TEXT,
    "linkedin_opportunity" TEXT,
    "linkedin_pending_summary" TEXT,
    "tags" TEXT
);

DROP TABLE IF EXISTS lead_emails CASCADE;
CREATE TABLE lead_emails (
    "lead_id" TEXT,
    "email" TEXT,
    "primary" TEXT,
    "email_status" TEXT,
    "label" TEXT
);

DROP TABLE IF EXISTS lead_phones CASCADE;
CREATE TABLE lead_phones (
    "lead_id" TEXT,
    "other_phone_number" TEXT,
    "label" TEXT
);

DROP TABLE IF EXISTS users CASCADE;
CREATE TABLE users (
    "id" TEXT,
    "user_name" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "email" TEXT,
    "job_title" TEXT,
    "work" TEXT,
    "mobile" TEXT,
    "time_zone" TEXT,
    "user_access_scope" TEXT,
    "is_active" TEXT,
    "language" TEXT,
    "last_login_time" TEXT
);

DROP TABLE IF EXISTS user_roles CASCADE;
CREATE TABLE user_roles (
    "id" TEXT,
    "user_id" TEXT,
    "user_name" TEXT,
    "role_id" TEXT,
    "role_name" TEXT
);

DROP TABLE IF EXISTS notes CASCADE;
CREATE TABLE notes (
    "id" TEXT,
    "description" TEXT,
    "created_by_id" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "extra_1" TEXT
);

DROP TABLE IF EXISTS note_targets CASCADE;
CREATE TABLE note_targets (
    "id" TEXT,
    "note_id" TEXT,
    "related_to_id" TEXT,
    "related_to_type" TEXT
);

DROP TABLE IF EXISTS tasks CASCADE;
CREATE TABLE tasks (
    "id" TEXT,
    "title" TEXT,
    "description" TEXT,
    "status" TEXT,
    "due_date" TEXT,
    "owner_id" TEXT,
    "created_by_id" TEXT,
    "updated_by_id" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "outcome" TEXT,
    "task_type" TEXT,
    "completed_date" TEXT
);

DROP TABLE IF EXISTS task_targets CASCADE;
CREATE TABLE task_targets (
    "id" TEXT,
    "task_id" TEXT,
    "related_to_id" TEXT,
    "related_to_type" TEXT
);

DROP TABLE IF EXISTS task_collaborators CASCADE;
CREATE TABLE task_collaborators (
    "id" TEXT,
    "task_id" TEXT,
    "user_id" TEXT
);

DROP TABLE IF EXISTS meetings CASCADE;
CREATE TABLE meetings (
    "id" TEXT,
    "title" TEXT,
    "description" TEXT,
    "from_date" TEXT,
    "to_date" TEXT,
    "location" TEXT,
    "created_by_id" TEXT,
    "updated_by_id" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "outcome" TEXT,
    "status" TEXT,
    "completed_date" TEXT
);

DROP TABLE IF EXISTS meeting_targets CASCADE;
CREATE TABLE meeting_targets (
    "id" TEXT,
    "appointment_id" TEXT,
    "related_to_id" TEXT,
    "related_to_type" TEXT
);

DROP TABLE IF EXISTS meeting_attendees CASCADE;
CREATE TABLE meeting_attendees (
    "id" TEXT,
    "appointment_id" TEXT,
    "attendee_id" TEXT,
    "attendee_type" TEXT
);

DROP TABLE IF EXISTS sales_activities CASCADE;
CREATE TABLE sales_activities (
    "id" TEXT,
    "title" TEXT,
    "description" TEXT,
    "start_date" TEXT,
    "end_date" TEXT,
    "outcome" TEXT,
    "sales_activity_type" TEXT,
    "created_by_id" TEXT,
    "created_by" TEXT,
    "updated_by_id" TEXT,
    "updated_by" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "import_id" TEXT,
    "status" TEXT,
    "completed_date" TEXT
);

DROP TABLE IF EXISTS salesactivity_targets CASCADE;
CREATE TABLE salesactivity_targets (
    "id" TEXT,
    "salesactivity_id" TEXT,
    "related_to_id" TEXT,
    "related_to_type" TEXT
);

DROP TABLE IF EXISTS salesactivity_collaborators CASCADE;
CREATE TABLE salesactivity_collaborators (
    "id" TEXT,
    "salesactivity_id" TEXT,
    "user_id" TEXT
);

DROP TABLE IF EXISTS call_logs CASCADE;
CREATE TABLE call_logs (
    "id" TEXT,
    "related_to_id" TEXT,
    "related_to_type" TEXT,
    "call_type" TEXT,
    "to_number" TEXT,
    "from_number" TEXT,
    "call_duration" TEXT,
    "call_status" TEXT,
    "call_cost" TEXT,
    "is_manual" TEXT,
    "user_id" TEXT,
    "created_at" TEXT,
    "updated_at" TEXT,
    "outcome" TEXT,
    "notes" TEXT,
    "recording_url" TEXT
);

-- Indexes on id columns for lookup speed

CREATE INDEX IF NOT EXISTS idx_accounts_id ON accounts(id);

CREATE INDEX IF NOT EXISTS idx_account_contacts_id ON account_contacts(id);

CREATE INDEX IF NOT EXISTS idx_contacts_id ON contacts(id);



CREATE INDEX IF NOT EXISTS idx_opportunities_id ON opportunities(id);

CREATE INDEX IF NOT EXISTS idx_opportunity_contacts_id ON opportunity_contacts(id);

CREATE INDEX IF NOT EXISTS idx_leads_id ON leads(id);



CREATE INDEX IF NOT EXISTS idx_users_id ON users(id);

CREATE INDEX IF NOT EXISTS idx_user_roles_id ON user_roles(id);

CREATE INDEX IF NOT EXISTS idx_notes_id ON notes(id);

CREATE INDEX IF NOT EXISTS idx_note_targets_id ON note_targets(id);

CREATE INDEX IF NOT EXISTS idx_tasks_id ON tasks(id);

CREATE INDEX IF NOT EXISTS idx_task_targets_id ON task_targets(id);

CREATE INDEX IF NOT EXISTS idx_task_collaborators_id ON task_collaborators(id);

CREATE INDEX IF NOT EXISTS idx_meetings_id ON meetings(id);

CREATE INDEX IF NOT EXISTS idx_meeting_targets_id ON meeting_targets(id);

CREATE INDEX IF NOT EXISTS idx_meeting_attendees_id ON meeting_attendees(id);

CREATE INDEX IF NOT EXISTS idx_sales_activities_id ON sales_activities(id);

CREATE INDEX IF NOT EXISTS idx_salesactivity_targets_id ON salesactivity_targets(id);

CREATE INDEX IF NOT EXISTS idx_salesactivity_collaborators_id ON salesactivity_collaborators(id);

CREATE INDEX IF NOT EXISTS idx_call_logs_id ON call_logs(id);
